# =============================================================================
# Block Builder — Week 2: Character Creation & Starting Resources
# =============================================================================
# NEW this week: variables, input(), int/float/str, arithmetic
# From before: print(), comments
#
# HOW TO USE THIS FILE
#   1. Copy EVERYTHING below the line into your game.py, replacing what's there
#   2. Fill in every TODO
#   3. Run it:   python game.py
#   4. Test it:  pytest tests/test_week02.py -v
#
# Do not edit this file — edit game.py.
# =============================================================================

# ------------------------- COPY FROM HERE -----------------------------------

# =============================================================================
# Block Builder — <your name here>
# =============================================================================

from rich import print

# --- Title screen ---
# This part is written for you. Change the colors or wording if you like!

print("=" * 50)
print("[bold green]        BLOCK BUILDER[/bold green]")
print("     A Survival Craft Adventure")
print("=" * 50)
print()

# --- Character creation (NEW: variables, input) ---

# TODO 1: Ask the player for their name and store it in a variable called `name`
#         Hint: name = input("What is your name, crafter? ")


print()

# Difficulty menu — written for you
print("Choose your difficulty:")
print("  1 - Peaceful  (extra resources, no monsters)")
print("  2 - Normal    (balanced start)")
print("  3 - Hardcore  (minimal resources, tough nights)")

# TODO 2: Ask for the difficulty and store it in a variable called `difficulty`


# --- Starting resources (NEW: variables) ---
# Every resource is a whole number, so these are all ints.
# Pick your own starting numbers if you want — just keep them sensible.

wood = 5
stone = 3
food = 10
water = 10
iron = 0
health = 100
day = 1

print()
print("Your name is: " + name)
print("You chose difficulty: " + difficulty)

# --- Arithmetic (NEW: +, -, *, //) ---

# TODO 3: Add up wood + stone + food + water + iron and store it
#         in a variable called `total_resources`


# TODO 4: Your crafter eats 2 food per day. Using integer division (//),
#         work out how many days the food will last.
#         Store it in a variable called `days_of_food`


# A basic shelter needs 4 walls at 5 wood each — written for you
walls_needed = 4
wood_per_wall = 5

# TODO 5: Multiply walls_needed by wood_per_wall to get `total_wood_needed`


# TODO 6: Subtract the wood you have from total_wood_needed to find out
#         how much more you need. Store it in `wood_shortage`


# --- Status display ---
# Remember: str() turns a number into text so you can join it onto a string.

print()
print("-" * 40)
print("[bold]Starting Status[/bold]")
print("-" * 40)
print("Name:    " + name)
print("Day:     " + str(day))
print("Health:  " + str(health))
print("-" * 40)
print("[bold cyan]Resources:[/bold cyan]")
print("  Wood:  " + str(wood) + " blocks")
print("  Stone: " + str(stone) + " blocks")
print("  Iron:  " + str(iron) + " ore")
print("  Food:  " + str(food) + " items")
print("  Water: " + str(water) + " units")
print("-" * 40)

# TODO 7: Print the total resources, using str() to join the number on.
#         It must include the word "Total" so the tests can find it.
#         Example: print("Total resources: " + str(total_resources))


# TODO 8: Print how many days the food will last, using days_of_food


print()

# TODO 9: Print how much wood a shelter needs and how much more you need,
#         using total_wood_needed and wood_shortage


print()
print("[bold green]Day " + str(day) + " begins. The sun is high. Start gathering![/bold green]")

# --------------------------- COPY TO HERE -----------------------------------
