# =============================================================================
# Block Builder — Week 3: Exploration Events & Choices
# =============================================================================
# NEW this week: if/elif/else, relational operators, and/or/not,
#                compound booleans, random
# From before: print(), variables, input(), arithmetic
# NOT yet: loops, functions
#
# HOW TO USE THIS FILE
#   This week you CHANGE one part of game.py and ADD three new parts.
#   Work through the four steps below in order, in your own game.py.
#   Keep your Week 2 title screen and character creation!
#
#   Run it:   python game.py
#   Test it:  pytest tests/test_week03.py -v
#
# Do not edit this file — edit game.py.
# =============================================================================


# =============================================================================
# STEP 1 — REPLACE your fixed starting resources with if/elif/else
# =============================================================================
# Last week difficulty didn't actually DO anything. This week it does.
#
# Find this block in your game.py:
#
#     wood = 5
#     stone = 3
#     food = 10
#     water = 10
#     iron = 0
#     health = 100
#     day = 1
#
# Replace the first five lines with the if/elif/else below, and keep
# `iron`, `health` and `day` after it.

# TODO 1: Fill in the resource values for each difficulty.
#         Peaceful should be the most generous, Hardcore the harshest.
#         Hardcore should also start with less than 100 health.

if difficulty == "1":
    mode = "Peaceful"
    # TODO: wood, stone, food, water, health

elif difficulty == "2":
    mode = "Normal"
    # TODO: wood, stone, food, water, health

else:
    mode = "Hardcore"
    # TODO: wood, stone, food, water, health

iron = 0
day = 1

print()
print("[bold]" + name + " spawns in " + mode + " mode![/bold]")


# =============================================================================
# STEP 2 — ADD an exploration event
# =============================================================================
# Add `import random` at the TOP of game.py, next to your rich import.
# Then add this section after your status display.

print()
print("-" * 50)
print("[bold]Day " + str(day) + " — Exploring the forest...[/bold]")
print("-" * 50)
print()

# TODO 2: Roll a random event number from 1 to 4
#         Hint: event = random.randint(1, 4)


# TODO 3: Write an if/elif/else chain with FOUR outcomes. You need at least
#         one that asks the player to make a choice with input().
#         Ideas below — change them, they're yours.
#
#   event == 1  A cave. Ask: enter (1) or stay outside (2)?
#               Entering: roll random.randint(1, 10). Over 5, find iron.
#               Otherwise, a bat bites you — lose health.
#               Staying outside: gather 3 wood safely.
#
#   event == 2  A wolf appears. Use a COMPOUND BOOLEAN to decide whether
#               you're in any shape to fight:
#                   if health > 70 and wood >= 3:
#               If you are, offer fight (1) or run (2).
#               If you aren't, you just take some damage.
#
#   event == 3  Bad weather. Roll a severity from 1 to 10 and use
#               if/elif/else: a storm costs health but collects water,
#               light rain just collects water, and clear skies do nothing.
#
#   else        A quiet day. Gather a random amount of wood and stone.
#
#         Remember: every branch should CHANGE at least one resource
#         variable, and print something so the player knows what happened.


# =============================================================================
# STEP 3 — ADD the night phase
# =============================================================================
# Shelter quality depends on how much wood you have left.

print()
print("-" * 50)
print("[bold]Night falls...[/bold]")

# TODO 4: Make two boolean variables from comparisons.
#         has_enough_wood should be True when wood is 10 or more.
#         has_some_shelter should be True when wood is 5 or more.


# TODO 5: Use if/elif/else on those two booleans:
#         - enough wood      -> safe night, no damage
#         - some wood        -> cold night, lose 5-10 health (use random)
#         - not enough       -> exposed, lose 10-25 health (use random)
#         Print a different message for each.


# =============================================================================
# STEP 4 — ADD the end-of-day report
# =============================================================================

print()
print("-" * 50)
print("[bold]End of Day " + str(day) + "[/bold]")
print("Health: " + str(health))
print("Wood: " + str(wood) + "  Stone: " + str(stone) + "  Iron: " + str(iron))
print("Food: " + str(food) + "  Water: " + str(water))

# TODO 6: Warn the player using COMPOUND BOOLEANS.
#         - low health AND low food  -> a critical warning
#         - low health OR low food   -> a milder warning
#         - otherwise                -> congratulate them on surviving
#         Pick your own thresholds.


# TODO 7: Finally, if health has dropped to 0 or below, print a death message.
